# Comprehensive content for all Python course chapters
# This file contains detailed slide content for rich presentations

CHAPTERS = {
    1: {
        'title': 'Chapter 1: Introduction to Python',
        'subtitle': 'Variables, Data Types, and Basic Operations',
        'slides': [
            {
                'title': 'What is Programming?',
                'content': [
                    'Programming: Writing instructions for computers to follow',
                    'Programmers: People who write these instructions',
                    'Programs: Sets of instructions that make computers do useful things',
                    '',
                    'Why Learn Programming?',
                    '• Automate repetitive tasks',
                    '• Solve complex problems efficiently',
                    '• Create websites, apps, and games',
                    '• Analyze data and make predictions',
                    '• High demand skill in modern job market'
                ]
            },
            {
                'title': 'Why Python?',
                'content': [
                    'Easy to Read and Write',
                    '• Syntax is close to natural English',
                    '• Less punctuation than other languages',
                    '• Focus on solving problems, not syntax',
                    '',
                    'Versatile and Powerful',
                    '• Web development (Django, Flask)',
                    '• Data science and machine learning',
                    '• Automation and scripting',
                    '• Scientific computing',
                    '',
                    'Large Community',
                    '• Millions of developers worldwide',
                    '• Extensive libraries and packages',
                    '• Great learning resources'
                ]
            },
            {
                'title': 'Variables: Storing Information',
                'content': [
                    'Variables are named storage locations for data',
                    '',
                    'Creating Variables:',
                    'name = "Alice"',
                    'age = 25',
                    'height = 1.75',
                    '',
                    'Variable Naming Rules:',
                    '• Must start with letter or underscore',
                    '• Can contain letters, numbers, underscores',
                    '• Case-sensitive (age ≠ Age)',
                    '• Cannot use Python keywords (if, for, while)',
                    '',
                    'Good Names: student_name, total_score, user_age',
                    'Bad Names: x, temp, data (too vague)'
                ]
            },
            {
                'title': 'Data Types: Numbers',
                'content': [
                    'Integers (int): Whole numbers',
                    '• Examples: 42, -17, 0, 1000',
                    '• Used for counting, indexing',
                    '',
                    'Floats (float): Decimal numbers',
                    '• Examples: 3.14, -0.5, 2.0',
                    '• Used for measurements, calculations',
                    '',
                    'Type Checking:',
                    'type(42)      # <class \'int\'>',
                    'type(3.14)    # <class \'float\'>',
                    '',
                    'Converting Between Types:',
                    'int(3.9)      # 3 (truncates)',
                    'float(42)     # 42.0'
                ]
            },
            {
                'title': 'Data Types: Strings',
                'content': [
                    'Strings (str): Text data',
                    '• Enclosed in quotes: "..." or \'...\'',
                    '• Examples: "Hello", \'Python\', "123"',
                    '',
                    'String Operations:',
                    'Concatenation: "Hello" + " " + "World"',
                    'Repetition: "Ha" * 3  # "HaHaHa"',
                    '',
                    'F-Strings (Formatted Strings):',
                    'name = "Alice"',
                    'age = 25',
                    'f"My name is {name} and I am {age}"',
                    '',
                    'Multi-line Strings:',
                    'Use triple quotes """..."""'
                ]
            },
            {
                'title': 'Arithmetic Operations',
                'content': [
                    'Basic Operations:',
                    '• Addition: 5 + 3 = 8',
                    '• Subtraction: 10 - 4 = 6',
                    '• Multiplication: 6 * 7 = 42',
                    '• Division: 15 / 3 = 5.0 (always float)',
                    '',
                    'Advanced Operations:',
                    '• Power: 2 ** 3 = 8 (2³)',
                    '• Floor Division: 17 // 5 = 3 (rounds down)',
                    '• Modulus: 17 % 5 = 2 (remainder)',
                    '',
                    'Operator Precedence (PEMDAS):',
                    '1. Parentheses ()',
                    '2. Exponents **',
                    '3. Multiplication *, Division /, Modulus %',
                    '4. Addition +, Subtraction -'
                ]
            },
            {
                'title': 'Operations with Variables',
                'content': [
                    'Using Variables in Calculations:',
                    'length = 10',
                    'width = 5',
                    'area = length * width  # 50',
                    '',
                    'Updating Variables:',
                    'score = 100',
                    'score = score + 10  # 110',
                    '',
                    'Shorthand Operators:',
                    '• score += 10  # Same as: score = score + 10',
                    '• score -= 5   # Same as: score = score - 5',
                    '• score *= 2   # Same as: score = score * 2',
                    '• score /= 4   # Same as: score = score / 4',
                    '',
                    'Multiple Operations:',
                    'total = (price * quantity) + tax'
                ]
            },
            {
                'title': 'The print() Function',
                'content': [
                    'Displaying Output to Screen:',
                    'print("Hello")  # Displays: Hello',
                    '',
                    'Printing Multiple Items:',
                    'print("Name:", name, "Age:", age)',
                    '',
                    'Print with Separators:',
                    'print("A", "B", "C", sep="-")  # A-B-C',
                    '',
                    'Print without Newline:',
                    'print("Hello", end=" ")',
                    'print("World")  # Hello World',
                    '',
                    'Formatted Output:',
                    'price = 19.99',
                    'print(f"Price: ${price:.2f}")  # Price: $19.99',
                    '',
                    'Escape Sequences:',
                    '\\n = newline, \\t = tab, \\\\ = backslash'
                ]
            },
            {
                'title': 'Comments and Code Documentation',
                'content': [
                    'Comments: Notes for humans, ignored by Python',
                    '',
                    'Single-line Comments:',
                    '# This is a comment',
                    'age = 25  # This explains the variable',
                    '',
                    'Multi-line Comments:',
                    '"""',
                    'This is a multi-line comment',
                    'Useful for longer explanations',
                    '"""',
                    '',
                    'When to Use Comments:',
                    '• Explain complex logic',
                    '• Document function purposes',
                    '• Add TODO notes',
                    '• Clarify tricky code',
                    '',
                    'Good Comment: # Calculate tax as 15% of price',
                    'Bad Comment: # Add 5 to x'
                ]
            },
            {
                'title': 'Real-World Applications',
                'content': [
                    'Temperature Converter:',
                    'celsius = 25',
                    'fahrenheit = (celsius * 9/5) + 32',
                    '',
                    'Shopping Calculator:',
                    'price = 50',
                    'quantity = 3',
                    'tax_rate = 0.08',
                    'total = (price * quantity) * (1 + tax_rate)',
                    '',
                    'Age Calculator:',
                    'birth_year = 2000',
                    'current_year = 2025',
                    'age = current_year - birth_year',
                    '',
                    'BMI Calculator:',
                    'weight = 70  # kg',
                    'height = 1.75  # meters',
                    'bmi = weight / (height ** 2)'
                ]
            },
            {
                'title': 'Common Mistakes to Avoid',
                'content': [
                    'Syntax Errors:',
                    '• Forgetting quotes: name = Alice (ERROR)',
                    '• Correct: name = "Alice"',
                    '',
                    'Type Errors:',
                    '• Mixing types: "5" + 3 (ERROR)',
                    '• Correct: int("5") + 3 or "5" + str(3)',
                    '',
                    'Variable Name Errors:',
                    '• Using keywords: for = 5 (ERROR)',
                    '• Starting with number: 2nd_place (ERROR)',
                    '• Correct: second_place',
                    '',
                    'Case Sensitivity:',
                    '• Name ≠ name ≠ NAME',
                    '',
                    'Undefined Variables:',
                    '• print(total) before defining total'
                ]
            },
            {
                'title': 'Key Concepts Review',
                'content': [
                    'Variables: Named storage for data',
                    '• Assignment: variable_name = value',
                    '• Can be updated: x = x + 1',
                    '',
                    'Data Types:',
                    '• int: Whole numbers (42, -10)',
                    '• float: Decimals (3.14, -0.5)',
                    '• str: Text ("Hello", \'Python\')',
                    '',
                    'Operations:',
                    '• Arithmetic: +, -, *, /, //, %, **',
                    '• Assignment: =, +=, -=, *=, /=',
                    '',
                    'Functions:',
                    '• print(): Display output',
                    '• type(): Check data type',
                    '• int(), float(), str(): Convert types',
                    '',
                    'Best Practices:',
                    '• Use descriptive variable names',
                    '• Add comments for clarity',
                    '• Test code frequently'
                ]
            }
        ]
    },
    2: {
        'title': 'Chapter 2: Working with Data',
        'subtitle': 'User Input, Type Conversion, and String Manipulation',
        'slides': [
            {
                'title': 'Getting User Input',
                'content': [
                    'The input() Function:',
                    'name = input("Enter your name: ")',
                    '',
                    'How it Works:',
                    '1. Displays prompt to user',
                    '2. Waits for user to type and press Enter',
                    '3. Returns what user typed as a string',
                    '4. Stores result in variable',
                    '',
                    'Important: input() Always Returns a String',
                    'age = input("Age: ")  # age is "25", not 25',
                    '',
                    'Creating Interactive Programs:',
                    'name = input("What is your name? ")',
                    'print("Hello,", name)',
                    '',
                    'Multiple Inputs:',
                    'first = input("First name: ")',
                    'last = input("Last name: ")',
                    'print(f"Full name: {first} {last}")'
                ]
            },
            {
                'title': 'Type Conversion (Casting)',
                'content': [
                    'Converting Between Data Types:',
                    '',
                    'String to Integer:',
                    'age_str = "25"',
                    'age_int = int(age_str)  # 25',
                    '',
                    'String to Float:',
                    'price_str = "19.99"',
                    'price_float = float(price_str)  # 19.99',
                    '',
                    'Number to String:',
                    'age = 25',
                    'age_str = str(age)  # "25"',
                    '',
                    'Converting User Input:',
                    'age = int(input("Enter age: "))',
                    'height = float(input("Enter height: "))',
                    '',
                    'Common Pattern:',
                    'number = int(input("Enter number: "))',
                    'result = number * 2'
                ]
            },
            {
                'title': 'String Indexing',
                'content': [
                    'Accessing Individual Characters:',
                    'text = "Python"',
                    '',
                    'Positive Indexing (from start):',
                    'text[0]  # "P" (first character)',
                    'text[1]  # "y"',
                    'text[5]  # "n" (last character)',
                    '',
                    'Negative Indexing (from end):',
                    'text[-1]  # "n" (last character)',
                    'text[-2]  # "o"',
                    'text[-6]  # "P" (first character)',
                    '',
                    'Index Range:',
                    '• Valid indices: 0 to length-1',
                    '• Or: -length to -1',
                    '',
                    'Length of String:',
                    'len(text)  # 6',
                    '',
                    'Index Out of Range Error:',
                    'text[10]  # ERROR!'
                ]
            },
            {
                'title': 'String Slicing',
                'content': [
                    'Extracting Substrings:',
                    'text = "Python Programming"',
                    '',
                    'Basic Slicing:',
                    'text[0:6]   # "Python"',
                    'text[7:18]  # "Programming"',
                    '',
                    'Shorthand Forms:',
                    'text[:6]    # "Python" (start to 6)',
                    'text[7:]    # "Programming" (7 to end)',
                    'text[:]     # "Python Programming" (entire)',
                    '',
                    'Step Parameter:',
                    'text[::2]   # "Pto rgamn" (every 2nd char)',
                    'text[::-1]  # "gnimmargorP nohtyP" (reversed)',
                    '',
                    'Slicing Pattern:',
                    'string[start:end:step]',
                    '• start: included',
                    '• end: excluded',
                    '• step: interval'
                ]
            },
            {
                'title': 'String Methods: Case Conversion',
                'content': [
                    'Changing Case:',
                    'text = "Python Programming"',
                    '',
                    'text.upper()',
                    '# "PYTHON PROGRAMMING"',
                    '',
                    'text.lower()',
                    '# "python programming"',
                    '',
                    'text.title()',
                    '# "Python Programming"',
                    '',
                    'text.capitalize()',
                    '# "Python programming"',
                    '',
                    'text.swapcase()',
                    '# "pYTHON pROGRAMMING"',
                    '',
                    'Practical Use:',
                    'name = input("Name: ").title()',
                    'command = input("Command: ").lower()',
                    '',
                    'Case-Insensitive Comparison:',
                    'if user_input.lower() == "yes":'
                ]
            },
            {
                'title': 'String Methods: Whitespace',
                'content': [
                    'Removing Whitespace:',
                    'text = "  Python  "',
                    '',
                    'text.strip()',
                    '# "Python" (both ends)',
                    '',
                    'text.lstrip()',
                    '# "Python  " (left side)',
                    '',
                    'text.rstrip()',
                    '# "  Python" (right side)',
                    '',
                    'Why This Matters:',
                    'name = input("Name: ").strip()',
                    '# Removes accidental spaces',
                    '',
                    'Removing Specific Characters:',
                    'text = "***Python***"',
                    'text.strip("*")  # "Python"',
                    '',
                    'Common Pattern:',
                    'user_input = input("Enter: ").strip().lower()'
                ]
            },
            {
                'title': 'String Methods: Search and Replace',
                'content': [
                    'Finding Substrings:',
                    'text = "Python is awesome"',
                    '',
                    'text.find("is")',
                    '# 7 (index where "is" starts)',
                    '',
                    'text.find("Java")',
                    '# -1 (not found)',
                    '',
                    'Checking if Substring Exists:',
                    '"Python" in text  # True',
                    '"Java" in text    # False',
                    '',
                    'Counting Occurrences:',
                    'text.count("o")  # 2',
                    '',
                    'Replacing Text:',
                    'text.replace("awesome", "powerful")',
                    '# "Python is powerful"',
                    '',
                    'Replace All Occurrences:',
                    'text = "ha ha ha"',
                    'text.replace("ha", "he")  # "he he he"'
                ]
            },
            {
                'title': 'String Methods: Split and Join',
                'content': [
                    'Splitting Strings into Lists:',
                    'text = "Python is awesome"',
                    'words = text.split()',
                    '# ["Python", "is", "awesome"]',
                    '',
                    'Split by Custom Separator:',
                    'csv = "John,Doe,25,NYC"',
                    'data = csv.split(",")',
                    '# ["John", "Doe", "25", "NYC"]',
                    '',
                    'Joining Lists into Strings:',
                    'words = ["Python", "is", "awesome"]',
                    '" ".join(words)',
                    '# "Python is awesome"',
                    '',
                    'Join with Different Separator:',
                    '"-".join(words)',
                    '# "Python-is-awesome"',
                    '',
                    'Practical Example:',
                    'path_parts = ["home", "user", "documents"]',
                    'path = "/".join(path_parts)',
                    '# "home/user/documents"'
                ]
            },
            {
                'title': 'String Formatting with F-Strings',
                'content': [
                    'F-Strings (Formatted String Literals):',
                    'name = "Alice"',
                    'age = 25',
                    'f"My name is {name} and I am {age}"',
                    '',
                    'Expressions in F-Strings:',
                    'f"Next year I will be {age + 1}"',
                    'f"Twice my age is {age * 2}"',
                    '',
                    'Formatting Numbers:',
                    'price = 19.99',
                    'f"Price: ${price:.2f}"  # $19.99',
                    '',
                    'pi = 3.14159265',
                    'f"Pi: {pi:.2f}"  # 3.14',
                    'f"Pi: {pi:.4f}"  # 3.1416',
                    '',
                    'Alignment:',
                    'f"{name:>10}"  # Right align in 10 spaces',
                    'f"{name:<10}"  # Left align',
                    'f"{name:^10}"  # Center align',
                    '',
                    'Multiple Variables:',
                    'f"{name} is {age} years old and lives in {city}"'
                ]
            },
            {
                'title': 'String Validation Methods',
                'content': [
                    'Checking String Content:',
                    '',
                    'text.isalpha()',
                    '# True if all letters',
                    '',
                    'text.isdigit()',
                    '# True if all digits',
                    '',
                    'text.isalnum()',
                    '# True if letters and/or digits',
                    '',
                    'text.isspace()',
                    '# True if all whitespace',
                    '',
                    'text.isupper()',
                    '# True if all uppercase',
                    '',
                    'text.islower()',
                    '# True if all lowercase',
                    '',
                    'Practical Use Cases:',
                    'if password.isalnum():',
                    '    print("Valid password")',
                    '',
                    'if user_input.isdigit():',
                    '    number = int(user_input)'
                ]
            },
            {
                'title': 'Escape Sequences',
                'content': [
                    'Special Characters in Strings:',
                    '',
                    'Newline (\\n):',
                    'print("Line 1\\nLine 2")',
                    '# Line 1',
                    '# Line 2',
                    '',
                    'Tab (\\t):',
                    'print("Name:\\tJohn")',
                    '# Name:    John',
                    '',
                    'Backslash (\\\\):',
                    'print("C:\\\\Users\\\\Documents")',
                    '# C:\\Users\\Documents',
                    '',
                    'Quotes Inside Strings:',
                    'print("She said \\"Hello\\"")',
                    "print('It\\'s Python')",
                    '',
                    'Raw Strings (r"..."):',
                    'path = r"C:\\Users\\Documents"',
                    '# No escape processing'
                ]
            },
            {
                'title': 'Building Interactive Programs',
                'content': [
                    'Complete Example: Personal Profile',
                    '',
                    '# Get user information',
                    'name = input("Name: ").strip().title()',
                    'age = int(input("Age: "))',
                    'city = input("City: ").strip().title()',
                    'hobby = input("Favorite hobby: ")',
                    '',
                    '# Create formatted profile',
                    'profile = f"""',
                    '========== PROFILE ==========',
                    'Name: {name}',
                    'Age: {age}',
                    'City: {city}',
                    'Hobby: {hobby}',
                    '=============================',
                    '"""',
                    '',
                    'print(profile)',
                    '',
                    'Key Techniques:',
                    '• strip() to clean input',
                    '• title() for proper capitalization',
                    '• int() for numeric conversion',
                    '• f-strings for formatting'
                ]
            },
            {
                'title': 'Common Patterns and Best Practices',
                'content': [
                    'Pattern 1: Clean User Input',
                    'user_input = input("Enter: ").strip().lower()',
                    '',
                    'Pattern 2: Validate Before Converting',
                    'age_str = input("Age: ")',
                    'if age_str.isdigit():',
                    '    age = int(age_str)',
                    '',
                    'Pattern 3: Build Formatted Output',
                    'data = [name, str(age), city]',
                    'csv_line = ",".join(data)',
                    '',
                    'Best Practices:',
                    '• Always strip() user input',
                    '• Convert types explicitly',
                    '• Use f-strings for readability',
                    '• Validate before processing',
                    '',
                    'Common Mistakes to Avoid:',
                    '• Forgetting input() returns string',
                    '• Not handling edge cases (empty input)',
                    '• Mixing + with strings and numbers'
                ]
            }
        ]
    },
    3: {
        'title': 'Chapter 3: Making Decisions',
        'subtitle': 'Conditional Statements and Boolean Logic',
        'slides': [
            {
                'title': 'Boolean Values: True and False',
                'content': [
                    'Boolean Data Type:',
                    '• Only two values: True and False',
                    '• Used for decision making',
                    '• Result of comparisons',
                    '',
                    'Creating Booleans:',
                    'is_student = True',
                    'is_raining = False',
                    '',
                    'Boolean from Comparisons:',
                    'age = 25',
                    'is_adult = age >= 18  # True',
                    '',
                    'Type Checking:',
                    'type(True)  # <class \'bool\'>',
                    '',
                    'Boolean in Conditions:',
                    'if is_student:',
                    '    print("Student discount available")',
                    '',
                    'Important: Capitalization Matters',
                    '• True and False (capital T and F)',
                    '• true and false are invalid'
                ]
            },
            {
                'title': 'Comparison Operators',
                'content': [
                    'Comparing Values:',
                    '',
                    'Equal to (==):',
                    '5 == 5   # True',
                    '5 == 3   # False',
                    '"hello" == "hello"  # True',
                    '',
                    'Not equal to (!=):',
                    '5 != 3   # True',
                    '5 != 5   # False',
                    '',
                    'Greater than (>):',
                    '10 > 5   # True',
                    '3 > 10   # False',
                    '',
                    'Less than (<):',
                    '3 < 10   # True',
                    '10 < 5   # False',
                    '',
                    'Greater than or equal (>=):',
                    '10 >= 10  # True',
                    '10 >= 5   # True',
                    '',
                    'Less than or equal (<=):',
                    '5 <= 10   # True',
                    '5 <= 5    # True'
                ]
            },
            {
                'title': 'The if Statement',
                'content': [
                    'Basic if Statement:',
                    'if condition:',
                    '    # code runs if condition is True',
                    '',
                    'Example:',
                    'age = 20',
                    'if age >= 18:',
                    '    print("You can vote")',
                    '',
                    'Important: Indentation Matters',
                    '• Use 4 spaces for indentation',
                    '• All code in the block must be indented',
                    '• Inconsistent indentation causes errors',
                    '',
                    'Multiple Statements:',
                    'if age >= 18:',
                    '    print("You are an adult")',
                    '    print("You have full rights")',
                    '    print("You can vote")',
                    '',
                    'if Statement Flow:',
                    '1. Evaluate condition',
                    '2. If True, execute indented code',
                    '3. If False, skip indented code',
                    '4. Continue with rest of program'
                ]
            },
            {
                'title': 'The if-else Statement',
                'content': [
                    'if-else Structure:',
                    'if condition:',
                    '    # runs if True',
                    'else:',
                    '    # runs if False',
                    '',
                    'Example:',
                    'age = 15',
                    'if age >= 18:',
                    '    print("Adult")',
                    'else:',
                    '    print("Minor")',
                    '',
                    'Practical Example: Login Check',
                    'password = input("Enter password: ")',
                    'if password == "secret123":',
                    '    print("Access granted")',
                    'else:',
                    '    print("Access denied")',
                    '',
                    'When to Use:',
                    '• Two mutually exclusive outcomes',
                    '• Either one path or the other',
                    '• Never both',
                    '',
                    'Flow:',
                    '• Condition True → if block runs',
                    '• Condition False → else block runs'
                ]
            },
            {
                'title': 'The if-elif-else Statement',
                'content': [
                    'Multiple Conditions:',
                    'if condition1:',
                    '    # runs if condition1 is True',
                    'elif condition2:',
                    '    # runs if condition2 is True',
                    'elif condition3:',
                    '    # runs if condition3 is True',
                    'else:',
                    '    # runs if all conditions are False',
                    '',
                    'Example: Grade System',
                    'score = 85',
                    'if score >= 90:',
                    '    grade = "A"',
                    'elif score >= 80:',
                    '    grade = "B"',
                    'elif score >= 70:',
                    '    grade = "C"',
                    'elif score >= 60:',
                    '    grade = "D"',
                    'else:',
                    '    grade = "F"',
                    '',
                    'Important: Order Matters',
                    '• Checks conditions top to bottom',
                    '• Stops at first True condition',
                    '• Only one block executes'
                ]
            },
            {
                'title': 'Logical Operators: and',
                'content': [
                    'The and Operator:',
                    '• Both conditions must be True',
                    '• Result is True only if both are True',
                    '',
                    'Syntax:',
                    'if condition1 and condition2:',
                    '    # code',
                    '',
                    'Example:',
                    'age = 25',
                    'has_license = True',
                    'if age >= 18 and has_license:',
                    '    print("Can drive")',
                    '',
                    'Truth Table:',
                    'True and True   → True',
                    'True and False  → False',
                    'False and True  → False',
                    'False and False → False',
                    '',
                    'Multiple Conditions:',
                    'if age >= 18 and age <= 65 and has_license:',
                    '    print("Standard driver")',
                    '',
                    'Common Use Cases:',
                    '• Range checks',
                    '• Multiple requirements',
                    '• Validation checks'
                ]
            },
            {
                'title': 'Logical Operators: or',
                'content': [
                    'The or Operator:',
                    '• At least one condition must be True',
                    '• Result is True if any is True',
                    '',
                    'Syntax:',
                    'if condition1 or condition2:',
                    '    # code',
                    '',
                    'Example:',
                    'age = 10',
                    'if age < 12 or age > 65:',
                    '    print("Discounted ticket")',
                    '',
                    'Truth Table:',
                    'True or True   → True',
                    'True or False  → True',
                    'False or True  → True',
                    'False or False → False',
                    '',
                    'Practical Example:',
                    'day = "Saturday"',
                    'if day == "Saturday" or day == "Sunday":',
                    '    print("Weekend!")',
                    '',
                    'Common Use Cases:',
                    '• Alternative conditions',
                    '• Multiple valid options',
                    '• Fallback conditions'
                ]
            },
            {
                'title': 'Logical Operators: not',
                'content': [
                    'The not Operator:',
                    '• Reverses boolean value',
                    '• True becomes False',
                    '• False becomes True',
                    '',
                    'Syntax:',
                    'if not condition:',
                    '    # code',
                    '',
                    'Example:',
                    'is_raining = False',
                    'if not is_raining:',
                    '    print("Go outside")',
                    '',
                    'Truth Table:',
                    'not True  → False',
                    'not False → True',
                    '',
                    'With Comparisons:',
                    'if not (age >= 18):',
                    '    print("Minor")',
                    '',
                    'Equivalent to:',
                    'if age < 18:',
                    '    print("Minor")',
                    '',
                    'Common Pattern:',
                    'if not username:',
                    '    print("Username required")'
                ]
            },
            {
                'title': 'Combining Logical Operators',
                'content': [
                    'Using Multiple Operators:',
                    '',
                    'Example 1: Age and Student Status',
                    'age = 20',
                    'is_student = True',
                    'if age < 25 and is_student:',
                    '    print("Student discount")',
                    '',
                    'Example 2: Complex Eligibility',
                    'if (age >= 18 and age <= 65) or has_permit:',
                    '    print("Can apply")',
                    '',
                    'Precedence Rules:',
                    '1. not (highest)',
                    '2. and',
                    '3. or (lowest)',
                    '',
                    'Use Parentheses for Clarity:',
                    'if (age >= 18 and has_license) or has_permit:',
                    '    # Clear intention',
                    '',
                    'Best Practices:',
                    '• Use parentheses for readability',
                    '• Break complex conditions into variables',
                    '• Comment complex logic'
                ]
            },
            {
                'title': 'Nested if Statements',
                'content': [
                    'if Statements Inside if Statements:',
                    '',
                    'Basic Structure:',
                    'if condition1:',
                    '    if condition2:',
                    '        # code',
                    '',
                    'Example:',
                    'age = 20',
                    'has_ticket = True',
                    '',
                    'if age >= 18:',
                    '    if has_ticket:',
                    '        print("Enjoy the show!")',
                    '    else:',
                    '        print("Please buy a ticket")',
                    'else:',
                    '    print("Too young")',
                    '',
                    'When to Use:',
                    '• Sequential decisions',
                    '• Dependent conditions',
                    '• Multi-level validation',
                    '',
                    'Alternative: Use and',
                    'if age >= 18 and has_ticket:',
                    '    print("Enjoy the show!")',
                    '',
                    'Best Practice:',
                    '• Limit nesting to 2-3 levels',
                    '• Consider using and/or instead',
                    '• Keep code readable'
                ]
            },
            {
                'title': 'Truthy and Falsy Values',
                'content': [
                    'Values That Act Like False:',
                    '• False',
                    '• None',
                    '• 0, 0.0',
                    '• "" (empty string)',
                    '• [] (empty list)',
                    '• {} (empty dictionary)',
                    '',
                    'Everything Else is Truthy:',
                    '• True',
                    '• Any non-zero number',
                    '• Any non-empty string',
                    '• Any non-empty collection',
                    '',
                    'Practical Use:',
                    'name = input("Name: ")',
                    'if name:  # True if not empty',
                    '    print(f"Hello, {name}")',
                    'else:',
                    '    print("Name required")',
                    '',
                    'Checking Empty Collections:',
                    'items = []',
                    'if items:',
                    '    print("Has items")',
                    'else:',
                    '    print("Empty list")'
                ]
            },
            {
                'title': 'Common Patterns and Best Practices',
                'content': [
                    'Pattern 1: Validation',
                    'if not username:',
                    '    print("Username required")',
                    'elif len(username) < 3:',
                    '    print("Username too short")',
                    'else:',
                    '    print("Valid username")',
                    '',
                    'Pattern 2: Range Checking',
                    'if 0 <= score <= 100:',
                    '    print("Valid score")',
                    '',
                    'Pattern 3: Menu Selection',
                    'choice = input("Choose (1-3): ")',
                    'if choice == "1":',
                    '    print("Option 1")',
                    'elif choice == "2":',
                    '    print("Option 2")',
                    'elif choice == "3":',
                    '    print("Option 3")',
                    'else:',
                    '    print("Invalid choice")',
                    '',
                    'Best Practices:',
                    '• Keep conditions simple',
                    '• Use descriptive variable names',
                    '• Handle all cases',
                    '• Avoid deep nesting'
                ]
            }
        ]
    },
    
    4: {
        'title': 'Chapter 4: Loops',
        'subtitle': 'Repetition with While and For Loops',
        'slides': [
            {
                'title': 'Why Do We Need Loops?',
                'content': [
                    'Problem: Repetitive Code',
                    'print("Hello")',
                    'print("Hello")',
                    'print("Hello")',
                    'print("Hello")',
                    'print("Hello")',
                    '',
                    'Solution: Use a Loop',
                    'for i in range(5):',
                    '    print("Hello")',
                    '',
                    'Benefits of Loops:',
                    '• Reduce code duplication',
                    '• Easy to change repetition count',
                    '• Handle variable-length tasks',
                    '• More efficient and maintainable',
                    '',
                    'Two Types of Loops in Python:',
                    '1. while loops: Repeat while condition is True',
                    '2. for loops: Repeat for each item in sequence'
                ]
            },
            {
                'title': 'While Loops: Basic Structure',
                'content': [
                    'While Loop Syntax:',
                    'while condition:',
                    '    # code to repeat',
                    '    # update condition eventually',
                    '',
                    'Simple Example:',
                    'count = 0',
                    'while count < 5:',
                    '    print(count)',
                    '    count += 1',
                    '',
                    'How It Works:',
                    '1. Check if condition is True',
                    '2. If True, execute loop body',
                    '3. Repeat from step 1',
                    '4. If False, exit loop',
                    '',
                    'Critical: Update Loop Variable',
                    '• Must change the condition eventually',
                    '• Otherwise: infinite loop',
                    '',
                    'Common Pattern:',
                    'counter = start_value',
                    'while counter < end_value:',
                    '    # do something',
                    '    counter += 1'
                ]
            },
            {
                'title': 'While Loop Examples',
                'content': [
                    'Countdown:',
                    'count = 5',
                    'while count > 0:',
                    '    print(count)',
                    '    count -= 1',
                    'print("Blast off!")',
                    '',
                    'Sum Numbers:',
                    'total = 0',
                    'num = 1',
                    'while num <= 10:',
                    '    total += num',
                    '    num += 1',
                    'print(f"Sum: {total}")',
                    '',
                    'User Input Loop:',
                    'password = ""',
                    'while password != "secret":',
                    '    password = input("Enter password: ")',
                    'print("Access granted")',
                    '',
                    'Validation Loop:',
                    'age = -1',
                    'while age < 0:',
                    '    age = int(input("Enter age: "))',
                    '    if age < 0:',
                    '        print("Age must be positive")'
                ]
            },
            {
                'title': 'For Loops: Basic Structure',
                'content': [
                    'For Loop Syntax:',
                    'for variable in sequence:',
                    '    # code to repeat',
                    '',
                    'Example with range():',
                    'for i in range(5):',
                    '    print(i)',
                    '# Prints: 0, 1, 2, 3, 4',
                    '',
                    'Example with String:',
                    'for char in "Python":',
                    '    print(char)',
                    '# Prints: P, y, t, h, o, n',
                    '',
                    'Example with List:',
                    'fruits = ["apple", "banana", "orange"]',
                    'for fruit in fruits:',
                    '    print(fruit)',
                    '',
                    'How It Works:',
                    '1. Get next item from sequence',
                    '2. Assign to loop variable',
                    '3. Execute loop body',
                    '4. Repeat until sequence ends',
                    '',
                    'Advantage:',
                    '• Automatically handles iteration',
                    '• No need to update counter'
                ]
            },
            {
                'title': 'The range() Function',
                'content': [
                    'range(stop): 0 to stop-1',
                    'range(5)  # 0, 1, 2, 3, 4',
                    'for i in range(5):',
                    '    print(i)',
                    '',
                    'range(start, stop): start to stop-1',
                    'range(2, 6)  # 2, 3, 4, 5',
                    'for i in range(2, 6):',
                    '    print(i)',
                    '',
                    'range(start, stop, step): with step',
                    'range(0, 10, 2)  # 0, 2, 4, 6, 8',
                    'for i in range(0, 10, 2):',
                    '    print(i)',
                    '',
                    'Negative Step (Countdown):',
                    'range(10, 0, -1)  # 10, 9, 8, ..., 1',
                    'for i in range(10, 0, -1):',
                    '    print(i)',
                    '',
                    'Converting to List:',
                    'list(range(5))  # [0, 1, 2, 3, 4]',
                    '',
                    'Common Patterns:',
                    'range(n)        # n times',
                    'range(1, n+1)   # 1 to n inclusive'
                ]
            },
            {
                'title': 'Break Statement',
                'content': [
                    'Exit Loop Early:',
                    '• Immediately exits the loop',
                    '• Skips remaining iterations',
                    '• Continues after loop',
                    '',
                    'Basic Example:',
                    'for i in range(10):',
                    '    if i == 5:',
                    '        break',
                    '    print(i)',
                    '# Prints: 0, 1, 2, 3, 4',
                    '',
                    'Search Example:',
                    'numbers = [3, 7, 2, 9, 5]',
                    'target = 9',
                    'for num in numbers:',
                    '    if num == target:',
                    '        print("Found!")',
                    '        break',
                    '',
                    'User Input Loop:',
                    'while True:',
                    '    command = input("Enter command: ")',
                    '    if command == "quit":',
                    '        break',
                    '    print(f"You entered: {command}")',
                    '',
                    'When to Use:',
                    '• Found what you\'re looking for',
                    '• Error condition detected',
                    '• User wants to exit'
                ]
            },
            {
                'title': 'Continue Statement',
                'content': [
                    'Skip to Next Iteration:',
                    '• Skips remaining code in loop body',
                    '• Moves to next iteration',
                    '• Loop continues running',
                    '',
                    'Basic Example:',
                    'for i in range(10):',
                    '    if i % 2 == 0:',
                    '        continue',
                    '    print(i)',
                    '# Prints: 1, 3, 5, 7, 9 (odd numbers)',
                    '',
                    'Skip Invalid Data:',
                    'numbers = [5, 0, 8, 0, 3]',
                    'for num in numbers:',
                    '    if num == 0:',
                    '        continue',
                    '    print(10 / num)',
                    '',
                    'Input Validation:',
                    'while True:',
                    '    name = input("Name: ")',
                    '    if not name:',
                    '        continue',
                    '    print(f"Hello, {name}")',
                    '    break',
                    '',
                    'Difference from break:',
                    '• break: exits loop completely',
                    '• continue: skips to next iteration'
                ]
            },
            {
                'title': 'Nested Loops',
                'content': [
                    'Loop Inside a Loop:',
                    '',
                    'Basic Structure:',
                    'for i in range(3):',
                    '    for j in range(3):',
                    '        print(f"i={i}, j={j}")',
                    '',
                    'Multiplication Table:',
                    'for i in range(1, 6):',
                    '    for j in range(1, 6):',
                    '        print(f"{i} x {j} = {i*j}")',
                    '',
                    'Pattern Printing:',
                    'for row in range(5):',
                    '    for col in range(row + 1):',
                    '        print("*", end="")',
                    '    print()  # New line',
                    '',
                    'Output:',
                    '*',
                    '**',
                    '***',
                    '****',
                    '*****',
                    '',
                    'How It Works:',
                    '• Outer loop runs once',
                    '• Inner loop completes all iterations',
                    '• Outer loop continues to next iteration',
                    '• Repeat'
                ]
            },
            {
                'title': 'Loop Performance and Infinite Loops',
                'content': [
                    'Infinite Loop: Loop Never Ends',
                    '',
                    'Common Causes:',
                    '',
                    '1. Forgot to Update Counter:',
                    'count = 0',
                    'while count < 5:',
                    '    print(count)',
                    '    # Missing: count += 1',
                    '',
                    '2. Wrong Update:',
                    'count = 0',
                    'while count < 5:',
                    '    print(count)',
                    '    count -= 1  # Goes backwards!',
                    '',
                    '3. Condition Never False:',
                    'while True:',
                    '    print("Forever")',
                    '    # No break statement',
                    '',
                    'How to Stop Infinite Loop:',
                    '• Press Ctrl+C in terminal',
                    '• Stop button in Jupyter/Colab',
                    '',
                    'Prevention:',
                    '• Always update loop variable',
                    '• Use break for while True loops',
                    '• Test with small iterations first',
                    '• Add safety counter if needed'
                ]
            },
            {
                'title': 'Choosing: While vs For',
                'content': [
                    'Use for loop when:',
                    '• You know how many iterations',
                    '• Iterating through a collection',
                    '• Using range() with known size',
                    '',
                    'for Examples:',
                    'for i in range(10):  # Repeat 10 times',
                    'for item in my_list:  # Process all items',
                    'for char in "Hello":  # Each character',
                    '',
                    'Use while loop when:',
                    '• Unknown number of iterations',
                    '• Condition-based repetition',
                    '• User input loops',
                    '• "Until something happens"',
                    '',
                    'while Examples:',
                    'while password != "correct":  # Until correct',
                    'while playing:  # Until game ends',
                    'while data_available:  # Until no more data',
                    '',
                    'Rule of Thumb:',
                    '• Default to for loops',
                    '• Use while for uncertain iterations',
                    '• for loops are often clearer and safer'
                ]
            },
            {
                'title': 'Common Loop Patterns',
                'content': [
                    'Pattern 1: Accumulator',
                    'total = 0',
                    'for num in range(1, 11):',
                    '    total += num',
                    '',
                    'Pattern 2: Counter',
                    'count = 0',
                    'for item in items:',
                    '    if condition:',
                    '        count += 1',
                    '',
                    'Pattern 3: Find First',
                    'for item in items:',
                    '    if item == target:',
                    '        found = True',
                    '        break',
                    '',
                    'Pattern 4: Build List',
                    'results = []',
                    'for i in range(10):',
                    '    results.append(i * 2)',
                    '',
                    'Pattern 5: Menu Loop',
                    'while True:',
                    '    choice = input("Choice: ")',
                    '    if choice == "quit":',
                    '        break',
                    '    process(choice)',
                    '',
                    'Pattern 6: Validation',
                    'while True:',
                    '    value = input("Enter: ")',
                    '    if is_valid(value):',
                    '        break',
                    '    print("Invalid, try again")'
                ]
            },
            {
                'title': 'Loop Best Practices',
                'content': [
                    'Good Practices:',
                    '',
                    '1. Use Meaningful Variable Names:',
                    'for student in students:  # Good',
                    'for i in students:        # Less clear',
                    '',
                    '2. Keep Loop Body Short:',
                    '• Extract complex logic to functions',
                    '• Max 10-15 lines per loop',
                    '',
                    '3. Avoid Modifying Loop Variable:',
                    'for i in range(10):',
                    '    i += 1  # Don\'t do this!',
                    '',
                    '4. Comment Complex Loops:',
                    '# Calculate running average',
                    'for value in data:',
                    '    ...',
                    '',
                    '5. Initialize Before Loop:',
                    'total = 0  # Initialize',
                    'for num in numbers:',
                    '    total += num',
                    '',
                    'Common Mistakes to Avoid:',
                    '• Infinite loops',
                    '• Off-by-one errors',
                    '• Forgetting to update counter',
                    '• Modifying collection while iterating'
                ]
            }
        ]
    },
    5: {
        'title': 'Chapter 5: Lists',
        'subtitle': 'Working with Ordered Collections',
        'slides': [
            {'title': 'What Are Lists?', 'content': ['Lists: Ordered collections of items', '• Can contain any data types', '• Mutable (can be changed)', '• Indexed starting at 0', '', 'Creating Lists:', 'fruits = ["apple", "banana", "orange"]', 'numbers = [1, 2, 3, 4, 5]', 'mixed = [1, "hello", 3.14, True]', 'empty = []', '', 'Why Use Lists?:', '• Store multiple related items', '• Organize data', '• Iterate through collections', '• Build dynamic datasets']},
            {'title': 'Accessing List Elements', 'content': ['Indexing:', 'fruits = ["apple", "banana", "orange"]', 'fruits[0]  # "apple"', 'fruits[1]  # "banana"', 'fruits[-1]  # "orange" (last)', '', 'Slicing:', 'fruits[0:2]  # ["apple", "banana"]', 'fruits[1:]   # ["banana", "orange"]', 'fruits[:2]   # ["apple", "banana"]', '', 'Length:', 'len(fruits)  # 3', '', 'Checking Membership:', '"apple" in fruits  # True', '"grape" not in fruits  # True']},
            {'title': 'Modifying Lists', 'content': ['Adding Items:', 'fruits.append("grape")  # Add to end', 'fruits.insert(1, "mango")  # Insert at index', 'fruits.extend(["kiwi", "pear"])  # Add multiple', '', 'Removing Items:', 'fruits.remove("banana")  # Remove by value', 'item = fruits.pop()  # Remove and return last', 'item = fruits.pop(0)  # Remove by index', 'del fruits[1]  # Delete by index', 'fruits.clear()  # Remove all', '', 'Changing Items:', 'fruits[0] = "pineapple"  # Change by index']},
            {'title': 'List Methods', 'content': ['Sorting:', 'numbers.sort()  # Sort in place', 'numbers.sort(reverse=True)  # Descending', 'sorted_nums = sorted(numbers)  # Return sorted copy', '', 'Reversing:', 'numbers.reverse()  # Reverse in place', 'reversed_nums = numbers[::-1]  # Copy reversed', '', 'Other Methods:', 'numbers.count(5)  # Count occurrences', 'numbers.index(3)  # Find first index', 'numbers.copy()  # Shallow copy', '', 'Concatenation:', 'list1 + list2  # Combine lists', '[1, 2] * 3  # [1, 2, 1, 2, 1, 2]']},
            {'title': 'Iterating Through Lists', 'content': ['Basic Iteration:', 'for fruit in fruits:', '    print(fruit)', '', 'With Index (enumerate):', 'for i, fruit in enumerate(fruits):', '    print(f"{i}: {fruit}")', '', 'With Index (range):', 'for i in range(len(fruits)):', '    print(f"{i}: {fruits[i]}")', '', 'List Comprehensions:', 'squares = [x**2 for x in range(10)]', 'evens = [x for x in numbers if x % 2 == 0]', '', 'Processing:', 'total = sum(numbers)', 'maximum = max(numbers)', 'minimum = min(numbers)']},
            {'title': 'Nested Lists', 'content': ['Lists Within Lists:', 'matrix = [', '    [1, 2, 3],', '    [4, 5, 6],', '    [7, 8, 9]', ']', '', 'Accessing:', 'matrix[0]  # [1, 2, 3]', 'matrix[0][0]  # 1', 'matrix[1][2]  # 6', '', 'Iterating:', 'for row in matrix:', '    for item in row:', '        print(item)', '', 'Use Cases:', '• 2D grids and boards', '• Tables of data', '• Coordinates', '• Multi-dimensional data']},
            {'title': 'Common List Patterns', 'content': ['Building Lists:', 'numbers = []', 'for i in range(10):', '    numbers.append(i * 2)', '', 'Filtering:', 'evens = []', 'for num in numbers:', '    if num % 2 == 0:', '        evens.append(num)', '', 'Finding Maximum:', 'max_val = numbers[0]', 'for num in numbers:', '    if num > max_val:', '        max_val = num', '', 'Copying Lists:', 'copy = original.copy()', 'copy = original[:]', 'copy = list(original)']},
            {'title': 'List Best Practices', 'content': ['Do:', '• Use descriptive names', '• Check for empty: if my_list:', '• Use list comprehensions for simple cases', '• Initialize before building', '', 'Avoid:', '• Modifying list while iterating', '• Using list as default parameter', '• Deep nesting (max 2-3 levels)', '', 'Common Mistakes:', '• Index out of range', '• Confusing append() and extend()', '• Forgetting lists are mutable', '• Not copying when needed', '', 'Performance:', '• append() is fast', '• insert(0, x) is slow', '• Use deque for frequent insertions']}
        ]
    },
    
    6: {
        'title': 'Chapter 6: Dictionaries',
        'subtitle': 'Key-Value Pairs and Mappings',
        'slides': [
            {'title': 'What Are Dictionaries?', 'content': ['Dictionaries: Collections of key-value pairs', '• Unordered (Python 3.7+: insertion ordered)', '• Keys must be unique', '• Values can be any type', '• Mutable', '', 'Creating Dictionaries:', 'student = {"name": "Alice", "age": 20}', 'empty = {}', 'empty = dict()', '', 'When to Use:', '• Associate related data', '• Fast lookup by key', '• Represent real-world objects', '• Configuration settings', '• Counting and grouping']},
            {'title': 'Accessing and Modifying', 'content': ['Access by Key:', 'student["name"]  # "Alice"', 'student.get("age")  # 20', 'student.get("grade", "N/A")  # Default', '', 'Adding/Updating:', 'student["grade"] = "A"  # Add new', 'student["age"] = 21  # Update', 'student.update({"gpa": 4.0})', '', 'Removing:', 'del student["age"]', 'grade = student.pop("grade")', 'student.clear()  # Remove all', '', 'Checking Keys:', '"name" in student  # True', '"email" not in student  # True']},
            {'title': 'Dictionary Methods', 'content': ['Keys, Values, Items:', 'student.keys()  # dict_keys([...])', 'student.values()  # dict_values([...])', 'student.items()  # dict_items([...])', '', 'Iterating:', 'for key in student:', '    print(key, student[key])', '', 'for key, value in student.items():', '    print(f"{key}: {value}")', '', 'Other Methods:', 'student.get(key, default)', 'student.setdefault(key, default)', 'student.update(other_dict)', 'student.copy()  # Shallow copy']},
            {'title': 'Dictionary Comprehensions', 'content': ['Creating from Lists:', 'keys = ["a", "b", "c"]', 'values = [1, 2, 3]', 'd = {k: v for k, v in zip(keys, values)}', '', 'Transforming:', 'squares = {x: x**2 for x in range(5)}', '# {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}', '', 'Filtering:', 'scores = {"Alice": 90, "Bob": 75, "Charlie": 85}', 'high_scores = {k: v for k, v in scores.items() if v >= 80}', '', 'Case Transform:', 'upper = {k.upper(): v for k, v in data.items()}']},
            {'title': 'Nested Dictionaries', 'content': ['Structure:', 'students = {', '    "student1": {"name": "Alice", "grade": "A"},', '    "student2": {"name": "Bob", "grade": "B"}', '}', '', 'Accessing:', 'students["student1"]["name"]  # "Alice"', '', 'Iterating:', 'for student_id, info in students.items():', '    print(f"{student_id}:")', '    for key, value in info.items():', '        print(f"  {key}: {value}")', '', 'Use Cases:', '• Database-like structures', '• Configuration files', '• API responses', '• Complex data models']},
            {'title': 'Common Patterns', 'content': ['Counting:', 'word_count = {}', 'for word in words:', '    word_count[word] = word_count.get(word, 0) + 1', '', 'Grouping:', 'by_grade = {}', 'for student in students:', '    grade = student["grade"]', '    if grade not in by_grade:', '        by_grade[grade] = []', '    by_grade[grade].append(student)', '', 'Merging:', 'dict1.update(dict2)', 'merged = {**dict1, **dict2}  # Python 3.5+', 'merged = dict1 | dict2  # Python 3.9+']},
            {'title': 'Dictionary vs List', 'content': ['Use Dictionary When:', '• Need key-value associations', '• Fast lookup is important', '• Keys are meaningful', '• Order doesn\'t matter much', '', 'Use List When:', '• Order is important', '• Need indexing by position', '• All items same type', '• Frequent iteration', '', 'Performance:', '• Dictionary lookup: O(1)', '• List search: O(n)', '• Dictionary more memory', '', 'Example:', 'phone_book = {"Alice": "555-1234"}  # Dict', 'names = ["Alice", "Bob"]  # List']},
            {'title': 'Best Practices', 'content': ['Good Practices:', '• Use .get() for safe access', '• Check keys before accessing', '• Use descriptive keys', '• Keep structure simple', '', 'Common Mistakes:', '• KeyError from missing key', '• Using mutable objects as keys', '• Not initializing nested structures', '• Comparing with == when need "is"', '', 'Performance Tips:', '• in operator is fast for keys', '• Use defaultdict for counting', '• Consider frozenset for immutable keys', '', 'Code Style:', '• One key-value per line for readability', '• Use trailing comma in multi-line']}
        ]
    },
    
    7: {
        'title': 'Chapter 7: Functions',
        'subtitle': 'Reusable Code and Modularity',
        'slides': [
            {'title': 'Why Functions?', 'content': ['Benefits:', '• Avoid code duplication (DRY)', '• Break down complex problems', '• Make code reusable', '• Easier to test and debug', '• Improve readability', '', 'Function Concept:', '• Input (parameters)', '• Processing (function body)', '• Output (return value)', '', 'Real-World Analogy:', '• Like a recipe: ingredients → steps → dish', '• Like a machine: input → process → output']},
            {'title': 'Defining Functions', 'content': ['Basic Syntax:', 'def function_name(parameters):', '    # function body', '    return value', '', 'Simple Example:', 'def greet(name):', '    return f"Hello, {name}!"', '', 'result = greet("Alice")  # "Hello, Alice!"', '', 'Multiple Statements:', 'def calculate_area(length, width):', '    area = length * width', '    return area', '', 'No Return:', 'def print_message():', '    print("Hello")  # Returns None']},
            {'title': 'Parameters and Arguments', 'content': ['Terminology:', '• Parameters: Variables in definition', '• Arguments: Values passed when calling', '', 'def add(a, b):  # a, b are parameters', '    return a + b', '', 'result = add(3, 5)  # 3, 5 are arguments', '', 'Types:', '• Positional: Order matters', '• Keyword: Name specified', '• Default: Optional with default value', '', 'add(3, 5)  # Positional', 'add(a=3, b=5)  # Keyword', 'add(b=5, a=3)  # Order doesn\'t matter']},
            {'title': 'Default Parameters', 'content': ['Syntax:', 'def greet(name, greeting="Hello"):', '    return f"{greeting}, {name}!"', '', 'Calling:', 'greet("Alice")  # "Hello, Alice!"', 'greet("Bob", "Hi")  # "Hi, Bob!"', 'greet("Charlie", greeting="Hey")  # "Hey, Charlie!"', '', 'Rules:', '• Default parameters must come last', '• Evaluated once at definition time', '• Don\'t use mutable defaults', '', 'Common Pattern:', 'def print_list(items, sep=", "):', '    print(sep.join(items))']},
            {'title': 'Return Values', 'content': ['Single Value:', 'def square(x):', '    return x ** 2', '', 'Multiple Values (Tuple):', 'def get_stats(numbers):', '    return min(numbers), max(numbers), sum(numbers)', '', 'min_val, max_val, total = get_stats([1, 2, 3, 4])', '', 'No Return (None):', 'def print_hello():', '    print("Hello")', '', 'result = print_hello()  # None', '', 'Early Return:', 'def divide(a, b):', '    if b == 0:', '        return None', '    return a / b']},
            {'title': 'Variable Scope', 'content': ['Local Scope:', 'def my_func():', '    local_var = 10  # Only exists in function', '    print(local_var)', '', 'Global Scope:', 'global_var = 20  # Exists everywhere', '', 'def my_func():', '    print(global_var)  # Can read global', '', 'Modifying Global:', 'count = 0', '', 'def increment():', '    global count  # Declare to modify', '    count += 1', '', 'Best Practice:', '• Avoid global variables when possible', '• Pass data through parameters', '• Return modified values']},
            {'title': 'Docstrings', 'content': ['Purpose: Document functions', '', 'Format:', 'def calculate_bmi(weight, height):', '    """', '    Calculate Body Mass Index.', '    ', '    Args:', '        weight (float): Weight in kg', '        height (float): Height in meters', '    ', '    Returns:', '        float: BMI value', '    """', '    return weight / (height ** 2)', '', 'Accessing:', 'print(calculate_bmi.__doc__)', 'help(calculate_bmi)', '', 'Best Practice:', '• Always document complex functions', '• Explain parameters and return values', '• Include usage examples']},
            {'title': 'Lambda Functions', 'content': ['Anonymous Functions:', 'lambda arguments: expression', '', 'Example:', 'square = lambda x: x ** 2', 'square(5)  # 25', '', 'Multiple Parameters:', 'add = lambda a, b: a + b', '', 'Common Use with sorted():', 'students = [', '    {"name": "Alice", "grade": 85},', '    {"name": "Bob", "grade": 92}', ']', 'sorted(students, key=lambda s: s["grade"])', '', 'When to Use:', '• Short, simple functions', '• As arguments to other functions', '• One-time use', '', 'When NOT to Use:', '• Complex logic', '• Multiple statements', '• Need documentation']},
            {'title': 'Best Practices', 'content': ['Function Design:', '• Do one thing well', '• Keep functions short (< 20 lines)', '• Use descriptive names', '• Document with docstrings', '', 'Parameters:', '• Limit to 3-4 parameters', '• Use default values wisely', '• Avoid mutable defaults', '', 'Return Values:', '• Be consistent with types', '• Return early on errors', '• Avoid returning None sometimes', '', 'Common Patterns:', '• Validation at start', '• Single return point (or early returns)', '• Clear variable names', '• Comments for complex logic']},
            {'title': 'Common Mistakes', 'content': ['Mistake 1: Forgetting return', 'def add(a, b):', '    result = a + b  # No return!', '', 'Mistake 2: Mutable default', 'def add_item(item, items=[]):', '    items.append(item)  # Dangerous!', '    return items', '', 'Fix:', 'def add_item(item, items=None):', '    if items is None:', '        items = []', '    items.append(item)', '    return items', '', 'Mistake 3: print vs return', 'def add(a, b):', '    print(a + b)  # Can\'t use result!', '', 'Mistake 4: Modifying arguments', '• Lists and dicts are mutable', '• Changes affect original']}
        ]
    },
    
    8: {
        'title': 'Chapter 8: Tuples and Sets',
        'subtitle': 'Immutable Sequences and Unique Collections',
        'slides': [
            {'title': 'Tuples: Immutable Sequences', 'content': ['What Are Tuples?', '• Ordered collections', '• Immutable (cannot be changed)', '• Can contain any types', '• Indexed like lists', '', 'Creating:', 'point = (10, 20)', 'person = ("Alice", 25, "NYC")', 'single = (42,)  # Note comma!', 'empty = ()', '', 'Why Use Tuples?', '• Protect data from changes', '• Use as dictionary keys', '• Return multiple values', '• Faster than lists', '• Less memory']},
            {'title': 'Working with Tuples', 'content': ['Accessing:', 'point = (10, 20, 30)', 'point[0]  # 10', 'point[-1]  # 30', 'point[0:2]  # (10, 20)', '', 'Unpacking:', 'x, y, z = point', 'first, *rest = (1, 2, 3, 4)', '', 'Operations:', 'len(point)  # 3', '20 in point  # True', '(1, 2) + (3, 4)  # (1, 2, 3, 4)', '(1, 2) * 3  # (1, 2, 1, 2, 1, 2)', '', 'Methods:', 'point.count(10)', 'point.index(20)', '', 'Cannot Modify:', 'point[0] = 15  # ERROR!']},
            {'title': 'Sets: Unique Collections', 'content': ['What Are Sets?', '• Unordered collections', '• No duplicates', '• Mutable', '• No indexing', '', 'Creating:', 'numbers = {1, 2, 3, 4, 5}', 'empty = set()  # NOT {}', 'from_list = set([1, 2, 2, 3])  # {1, 2, 3}', '', 'Why Use Sets?', '• Remove duplicates', '• Fast membership testing', '• Mathematical set operations', '• Track unique items']},
            {'title': 'Set Operations', 'content': ['Basic Operations:', 'numbers = {1, 2, 3}', 'numbers.add(4)', 'numbers.remove(2)  # Error if not found', 'numbers.discard(2)  # No error', 'numbers.pop()  # Remove arbitrary', '', 'Membership:', '3 in numbers  # O(1) - very fast!', '', 'Set Math:', 'a = {1, 2, 3}', 'b = {3, 4, 5}', '', 'a | b  # Union: {1, 2, 3, 4, 5}', 'a & b  # Intersection: {3}', 'a - b  # Difference: {1, 2}', 'a ^ b  # Symmetric diff: {1, 2, 4, 5}']},
            {'title': 'When to Use Each', 'content': ['Use Tuple When:', '• Data shouldn\'t change', '• Need hashable type', '• Return multiple values', '• Represent fixed structure', '', 'Examples:', 'coordinates = (x, y)', 'rgb_color = (255, 0, 128)', 'date = (2025, 1, 24)', '', 'Use Set When:', '• Need unique elements', '• Fast membership tests', '• Set operations needed', '• Order doesn\'t matter', '', 'Examples:', 'unique_ids = {101, 102, 103}', 'tags = {"python", "coding"}', 'visited_pages = set()']},
            {'title': 'Practical Examples', 'content': ['Remove Duplicates:', 'numbers = [1, 2, 2, 3, 3, 3]', 'unique = list(set(numbers))', '', 'Find Common Elements:', 'list1 = [1, 2, 3, 4]', 'list2 = [3, 4, 5, 6]', 'common = set(list1) & set(list2)', '', 'Multiple Return Values:', 'def get_stats(data):', '    return min(data), max(data), len(data)', '', 'min_val, max_val, count = get_stats([1,2,3])', '', 'Coordinate Pairs:', 'positions = {(0, 0), (1, 1), (2, 2)}', 'if (x, y) in positions:', '    print("Occupied")']}
        ]
    },
    
    9: {
        'title': 'Chapter 9: File I/O',
        'subtitle': 'Reading and Writing Files',
        'slides': [
            {'title': 'Why Work with Files?', 'content': ['Data Persistence:', '• Save data between program runs', '• Store user information', '• Log program activity', '• Import/export data', '', 'Common File Types:', '• Text files (.txt)', '• CSV files (.csv)', '• JSON files (.json)', '• Configuration files', '', 'File Operations:', '• Read: Get data from file', '• Write: Save data to file', '• Append: Add to existing file', '• Delete: Remove file']},
            {'title': 'Reading Files', 'content': ['Basic Pattern:', 'with open("file.txt", "r") as file:', '    content = file.read()', '', 'Reading Methods:', 'file.read()  # Entire file', 'file.readline()  # One line', 'file.readlines()  # List of lines', '', 'Iterating:', 'with open("file.txt", "r") as file:', '    for line in file:', '        print(line.strip())', '', 'Why use "with"?', '• Automatically closes file', '• Works even if error occurs', '• Best practice']},
            {'title': 'Writing Files', 'content': ['Write Mode (Overwrites):', 'with open("file.txt", "w") as file:', '    file.write("Hello\\n")', '    file.write("World\\n")', '', 'Append Mode (Adds to End):', 'with open("file.txt", "a") as file:', '    file.write("New line\\n")', '', 'Write Multiple Lines:', 'lines = ["Line 1\\n", "Line 2\\n"]', 'with open("file.txt", "w") as file:', '    file.writelines(lines)', '', 'Using print():', 'with open("file.txt", "w") as file:', '    print("Hello", file=file)']},
            {'title': 'Working with CSV Files', 'content': ['Reading CSV:', 'import csv', '', 'with open("data.csv", "r") as file:', '    reader = csv.reader(file)', '    for row in reader:', '        print(row)  # List of values', '', 'Using DictReader:', 'with open("data.csv", "r") as file:', '    reader = csv.DictReader(file)', '    for row in reader:', '        print(row["name"])', '', 'Writing CSV:', 'with open("data.csv", "w", newline="") as file:', '    writer = csv.writer(file)', '    writer.writerow(["Name", "Age"])', '    writer.writerow(["Alice", "25"])']},
            {'title': 'Working with JSON Files', 'content': ['Reading JSON:', 'import json', '', 'with open("data.json", "r") as file:', '    data = json.load(file)', '', 'Writing JSON:', 'data = {"name": "Alice", "age": 25}', '', 'with open("data.json", "w") as file:', '    json.dump(data, file, indent=4)', '', 'JSON Strings:', 'json_str = json.dumps(data)  # To string', 'data = json.loads(json_str)  # From string', '', 'Why JSON?', '• Human-readable', '• Language-independent', '• Supports nested structures', '• Common API format']},
            {'title': 'File Paths', 'content': ['Absolute Path:', '"/home/user/documents/file.txt"', '"C:\\\\Users\\\\Name\\\\file.txt"', '', 'Relative Path:', '"file.txt"  # Same directory', '"data/file.txt"  # Subdirectory', '"../file.txt"  # Parent directory', '', 'Using pathlib:', 'from pathlib import Path', '', 'path = Path("data") / "file.txt"', 'path.exists()', 'path.read_text()', 'path.write_text("content")', '', 'Best Practices:', '• Use Path for cross-platform', '• Check if file exists', '• Use absolute paths when possible']},
            {'title': 'Error Handling with Files', 'content': ['Common Errors:', '• FileNotFoundError', '• PermissionError', '• IsADirectoryError', '', 'Safe Reading:', 'try:', '    with open("file.txt", "r") as file:', '        content = file.read()', 'except FileNotFoundError:', '    print("File not found")', '    content = ""', '', 'Check Before Opening:', 'import os', '', 'if os.path.exists("file.txt"):', '    with open("file.txt", "r") as file:', '        content = file.read()', '', 'Directory Operations:', 'os.listdir(".")  # List files', 'os.makedirs("new_dir")', 'os.path.isfile("file.txt")']},
            {'title': 'Best Practices', 'content': ['Always Use "with":', '• Automatically closes files', '• Handles errors gracefully', '', 'Handle Errors:', '• Check if file exists', '• Use try-except', '• Provide helpful messages', '', 'Choose Right Format:', '• Text: Simple data', '• CSV: Tabular data', '• JSON: Structured data', '', 'Performance:', '• Read line-by-line for large files', '• Use buffering', '• Close files when done', '', 'Security:', '• Validate file paths', '• Don\'t trust user input', '• Check file size', '• Use appropriate permissions']}
        ]
    },
    
    10: {
        'title': 'Chapter 10: Error Handling',
        'subtitle': 'Writing Robust Python Code',
        'slides': [
            {'title': 'Why Error Handling?', 'content': ['Problems Without Handling:', '• Programs crash', '• Poor user experience', '• Lost data', '• No recovery', '', 'Benefits of Handling:', '• Graceful degradation', '• User-friendly messages', '• Program continues running', '• Logging and debugging', '', 'Types of Errors:', '• Syntax errors: Code won\'t run', '• Runtime errors: Crash during execution', '• Logic errors: Wrong results', '', 'We Focus On:', '• Runtime error handling', '• Exceptions management']},
            {'title': 'Common Exceptions', 'content': ['ValueError:', '• Invalid type conversion', '• int("abc")', '', 'ZeroDivisionError:', '• Division by zero', '• 10 / 0', '', 'TypeError:', '• Wrong type operation', '• "hello" + 5', '', 'IndexError:', '• Invalid list index', '• [1, 2][5]', '', 'KeyError:', '• Invalid dict key', '• {"a": 1}["b"]', '', 'FileNotFoundError:', '• File doesn\'t exist', '', 'AttributeError:', '• Invalid attribute access']},
            {'title': 'Try-Except Blocks', 'content': ['Basic Syntax:', 'try:', '    # Code that might raise exception', '    age = int(input("Age: "))', 'except ValueError:', '    # Handle the error', '    print("Please enter a number")', '', 'Multiple Exceptions:', 'try:', '    result = 10 / int(input("Number: "))', 'except ValueError:', '    print("Invalid number")', 'except ZeroDivisionError:', '    print("Cannot divide by zero")', '', 'Catch All:', 'except Exception as e:', '    print(f"Error: {e}")']},
            {'title': 'The else and finally Clauses', 'content': ['else Clause:', '• Runs if no exception occurred', '', 'try:', '    age = int(input("Age: "))', 'except ValueError:', '    print("Invalid")', 'else:', '    print(f"Valid age: {age}")', '', 'finally Clause:', '• Always runs, error or not', '• Used for cleanup', '', 'try:', '    file = open("data.txt")', '    data = file.read()', 'except FileNotFoundError:', '    print("File not found")', 'finally:', '    file.close()  # Always closes']},
            {'title': 'Raising Exceptions', 'content': ['raise Keyword:', '• Trigger exceptions manually', '', 'def set_age(age):', '    if age < 0:', '        raise ValueError("Age cannot be negative")', '    if age > 150:', '        raise ValueError("Age too high")', '    return age', '', 'try:', '    user_age = set_age(-5)', 'except ValueError as e:', '    print(f"Error: {e}")', '', 'Re-raising:', 'try:', '    risky_operation()', 'except Exception:', '    log_error()', '    raise  # Re-raise same exception']},
            {'title': 'Custom Exceptions', 'content': ['Define Your Own:', 'class InvalidAgeError(Exception):', '    pass', '', 'class NegativeValueError(Exception):', '    def __init__(self, value):', '        self.value = value', '        super().__init__(f"Negative: {value}")', '', 'Using Custom Exceptions:', 'def validate_age(age):', '    if age < 0:', '        raise InvalidAgeError("Age must be positive")', '', 'try:', '    validate_age(-5)', 'except InvalidAgeError as e:', '    print(f"Validation error: {e}")', '', 'When to Use:', '• Domain-specific errors', '• Better error clarity', '• Custom error handling']},
            {'title': 'Validation Patterns', 'content': ['Pattern 1: Retry Loop', 'while True:', '    try:', '        age = int(input("Age: "))', '        if age < 0:', '            print("Must be positive")', '            continue', '        break', '    except ValueError:', '        print("Enter a number")', '', 'Pattern 2: Default Value', 'try:', '    config = load_config()', 'except FileNotFoundError:', '    config = default_config()', '', 'Pattern 3: Validation Function', 'def get_valid_int(prompt):', '    while True:', '        try:', '            return int(input(prompt))', '        except ValueError:', '            print("Invalid number")'  ]},
            {'title': 'Best Practices', 'content': ['Be Specific:', '• Catch specific exceptions', '• Avoid bare except', '', 'try:', '    value = int(input())', 'except ValueError:  # Good', '    handle_error()', '', 'try:', '    value = int(input())', 'except:  # Too broad', '    handle_error()', '', 'Provide Context:', '• Helpful error messages', '• Explain what went wrong', '• Suggest solution', '', 'Don\'t Silence Errors:', '• Avoid empty except blocks', '• Log or handle appropriately', '', 'Use finally for Cleanup:', '• Close files', '• Release resources', '• Restore state']},
            {'title': 'Common Mistakes', 'content': ['Mistake 1: Catching Too Broad', 'except Exception:  # Catches everything', '', 'Mistake 2: Silent Failures', 'try:', '    risky_code()', 'except:', '    pass  # Bad! Hides errors', '', 'Mistake 3: Wrong Exception', 'try:', '    items[index]', 'except ValueError:  # Should be IndexError', '    handle_error()', '', 'Mistake 4: Logic in except', '• Keep except blocks simple', '• Extract complex logic', '', 'Mistake 5: Not Using finally', '• Forgetting to close resources', '• Use "with" or finally']},
            {'title': 'When to Use Exceptions', 'content': ['Use Exceptions For:', '• Unexpected errors', '• External dependencies', '• User input validation', '• Resource management', '', 'Don\'t Use For:', '• Normal control flow', '• Expected conditions', '• Performance-critical code', '', 'Example - Good:', 'try:', '    file = open("config.json")', 'except FileNotFoundError:', '    use_defaults()', '', 'Example - Bad:', 'try:', '    if user in users:', '        login(user)', 'except KeyError:', '    create_user()', '', 'Better:', 'if user in users:', '    login(user)', 'else:', '    create_user()']}
        ]
    }
}
